run:
	gcc main.c
	./a.out "." "magic words" 1
	@echo "\nAnother One\n"
	./a.out "." "magic words" 15

	@echo "\nAnother One\n"
	./a.out "dir_a" "magic words" 10

	#@echo "\nAnother One\n"
	#./a.out "../.." "magic words" 15