run:
	gcc -Wall main.c -lpthread
	./a.out 8 numbers columns.ascii.pgm wynik1.ascii.pgn
	./a.out 8 block columns.ascii.pgm wynik2.ascii.pgn

test:
	gcc -Wall main.c -lpthread
	./a.out 1 numbers columns.ascii.pgm wynik1.ascii.pgn
	./a.out 1 block columns.ascii.pgm wynik2.ascii.pgn
	./a.out 2 numbers columns.ascii.pgm wynik1.ascii.pgn
	./a.out 2 block columns.ascii.pgm wynik2.ascii.pgn
	./a.out 4 numbers columns.ascii.pgm wynik1.ascii.pgn
	./a.out 4 block columns.ascii.pgm wynik2.ascii.pgn
	./a.out 8 numbers columns.ascii.pgm wynik1.ascii.pgn
	./a.out 8 block columns.ascii.pgm wynik2.ascii.pgn
	./a.out 16 numbers columns.ascii.pgm wynik1.ascii.pgn
	./a.out 16 block columns.ascii.pgm wynik2.ascii.pgn
